### PR TITLE
fix alias incoming transaction direction

### LINKED ISSUE #784: Incoming transaction send to alias presented as outgoind on receiver side
Steps:
1. Send the transaction from account A to namespace alias (from outside wallet because right now it's not possible) linked with account B.
2. Switch to account B and go to transactions.

Incoming transaction is presented as outgoing. 

image
image

We need to resolve namespace at time of sending. Not sure if API allows that. To fix this small issue lot of work may be required, I'm reporting anyway to have this in queue.

### PR DESCRIPTION
**Pull request by bassemmagdy**
- fix #784

### CODE REVIEW

File: src/core/transactions/ViewTransferTransaction.ts [hunk 1]
```diff
@@ -25,9 +25,23 @@ import { MosaicModel } from '@/core/database/entities/MosaicModel';
 export class ViewTransferTransaction extends TransactionView<TransferTransaction> {
     public get isIncoming() {
         const currentSignerAddress = this.$store.getters['account/currentSignerAddress'];
+        if (this.transaction.type === TransactionType.TRANSFER && this.transaction.recipientAddress instanceof NamespaceId) {
+            const linkedAddress = this.$store.getters['namespace/linkedAddress'];
+            if (!linkedAddress) {
+                this.checkLinkedAddress(this.transaction.recipientAddress);
+                return false;
```
Comment (rg911) [inline src/core/transactions/ViewTransferTransaction.ts:32]: why return false here, does it needs to recheck the linkedAddress after dispatch called?

Comment (bassemmagdy) [reply src/core/transactions/ViewTransferTransaction.ts:32]: yes, as GET_LINKED_ADDRESS is an async function and doesn't return the linked address so there must be a return statement to avoid sending multiple requests to fetch namespace linkedAdress.

**Review by rg911 — APPROVED** [review]
