### PR TITLE
multiple multisig account page issues fix & refactor, explorer uri fix

### LINKED ISSUE #513: Can't convert account to multi-sig with "Recommended" fee
Version: v0.12.1

Scenario: Converting account to 3 of 3 multi-sig doesn't work with the Recommended fee. It's created only hash lock transaction.
When we change fee to Fastest multisig-account is created.

Example (first conversion failed, second with higher fee succeed):
http://explorer-96x.symboldev.network/account/TDMB7MLZZIYTQJ2THNPPKHBCIJGQ3IEMMDO6PJQ

Steve mentioned SDK function that can be used to calculate the correct fee:

The SDK has created a method to calculate the max possible fees for aggregate tx. it takes required number of cosignateries and fee multiplier. https://github.com/nemtech/symbol-sdk-typescript-javascript/blob/9696f4ad65b9026e9c4acbddcbd6613d009148aa/src/model/transaction/AggregateTransaction.ts#L406
FeeMultiplier can be retrieved from network properties, and if required number of cosignateries not know, can use the total cosignateries for a safe pass.

### PR DESCRIPTION
**Pull request by yilmazbahadir**
fixes #513, #528, #540, #543, #550, #551

### CODE REVIEW

File: src/components/AddCosignatoryInput/AddCosignatoryInputTs.ts [hunk 1]
```diff
@@ -103,41 +103,12 @@ export class AddCosignatoryInputTs extends Vue {
   }
 
   /**
-   * Emits onAddCosignatory event when cosignatory is input as a public key
+   * Emits onAddCosignatory event when cosignatory is input as an address
    * @private
    * @return {void}
    */
   private async addCosignerFromAddress() {
-    const address = Address.createFromRawAddress(this.cosignatory)
```
Comment (evias) [inline src/components/AddCosignatoryInput/AddCosignatoryInputTs.ts:111]: as discussed on slack, this check should not be removed as this _prevents_ end-users from creating invalid transactions.

If this check is not done, and users are allowed to create multisig modifications with unknown cosigners ("unknown" as in "unknown by the network"), those transactions will be *invalid* and the end-users will end up being banned which we really want to avoid.

I suggested to add **steps** and **information** on how to solve the "account must be known" problem.

Also, _converting an unknown account to msig_ shall be fine. Whilst _adding cosigners that are unknown accounts_ is not fine.

**Review by evias — DISMISSED** [review]

File: src/components/AddCosignatoryInput/AddCosignatoryInputTs.ts (hunk 1 above)
Comment (yilmazbahadir) [reply src/components/AddCosignatoryInput/AddCosignatoryInputTs.ts:111]: As discussed on the daily since this is an existing problem with Public Key input as well, this will be handled with another issue( https://github.com/nemgrouplimited/symbol-desktop-wallet/issues/561 ), please exclude this concern from this review.

Comment (yilmazbahadir) [reply src/components/AddCosignatoryInput/AddCosignatoryInputTs.ts:111]: This concern is not valid any more after the 0.96 release. Please see the comment in #561 for the details.

**Review by bassemmagdy — APPROVED** [review]

**Review by bassemmagdy — APPROVED** [review]

**Review by rg911 — APPROVED** [review]
