### PR TITLE
Fix password copy paste

### LINKED ISSUE #1167: Copy & Past of the password when creating the wallet should not be accepted.
v0.14.0 linux

1) Fill in the password under "Password".
2) Filling in the password under "Confirm Your Password".
3) Error message that the passwords do not match.
4) Copy the password under "Confirm Your Password".
5) Paste the password under "Password".

If a user assumes that he/she made a mistake when entering the password under "Password", but the second entry under "Confirm Your Password" was correct, it should not be possible to copy the password from the second entry and paste it under "Password".
It also works the other way round.
This should not be possible.

### PR DESCRIPTION
**Pull request by bassemmagdy**
fixes #1167

### CODE REVIEW

File: src/components/PasswordInput/PasswordInput.vue [hunk 1]
```diff
@@ -0,0 +1,18 @@
+<template>
+    <input
+        :value="value"
```
Comment (AnthonyLaw) [inline src/components/PasswordInput/PasswordInput.vue:3]: I no sure are you still need the `value` as props.
because I didn't see you pass anything in `value` props

**Comment by AnthonyLaw** [comment]
you may need to add a unit test for the component.

**Review by AnthonyLaw — APPROVED** [review]
