### PR TITLE
fix error message while creating new profile on ledger

### LINKED ISSUE #1483: Cannot create profile using Ledger
I get the following error when trying to create a profile:

> Failed to create profile, reason: [object Object]

screenshot_symbol_wallet

**Platform:** Ubuntu 21.04
**Symbol wallet version:** 1.0.2

Using with Ledger Live (v. 2.26.1) and Ledger Nano S (firmware 2.0.0). Both are latest version at time of writing.

**What I did**

1. Fresh install on Ubuntu 21.04
2. Ledger Live unlocked, incl. Symbol app open on Ledger Nano S (optional)
3. Open Symbol Wallet and select "Access Ledger"
4. Complete information as per screenshot. Click "Next"

Same error occurs also without step 2. I included this just in case this is supposed to be required.

### PR DESCRIPTION
**Pull request by bassemmagdy**
fixes  #1483

### CODE REVIEW

**Comment by AnthonyLaw** [comment]
Tested: working
image

File: src/views/forms/FormProfileCreation/FormProfileCreationTs.ts [hunk 1]
```diff
@@ -155,6 +155,7 @@ export class FormProfileCreationTs extends Vue {
      * Error notification handler
      */
     private errorNotificationHandler(error: any) {
+        console.log(error.message, error.errorCode);
```
Comment (rg911) [inline src/views/forms/FormProfileCreation/FormProfileCreationTs.ts:158]: do we need a console log here?  same below

Comment (bassemmagdy) [reply src/views/forms/FormProfileCreation/FormProfileCreationTs.ts]: updated

**Review by AnthonyLaw — APPROVED** [review]

**Review by rg911 — APPROVED** [review]
